// src/components/TripResult.jsx
import { useState, useRef } from "react";
import client from "../api/client";
import useTranslate from "../hooks/useTranslate";
import jsPDF from "jspdf";
import TripCostSplitter from "./TripCostSplitter";
import WeatherBanner from "./WeatherBanner";
import WeatherCard from "./WeatherCard";
import HotelsCard from "./HotelsCard";
import TrainsCard from "./TrainsCard";

const Section = ({ title, icon, children }) => (
  <div className="rounded-2xl border p-4 md:p-6 mb-4" style={{ background: "rgba(255,255,255,0.07)", backdropFilter: "blur(20px)", WebkitBackdropFilter: "blur(20px)", border: "1px solid rgba(255,255,255,0.14)" }}>
    <div className="flex items-center gap-2.5 mb-4 md:mb-5">
      {icon && <div className="w-7 h-7 rounded-lg flex items-center justify-center shrink-0" style={{ background: "rgba(255,255,255,0.08)", border: "1px solid rgba(255,255,255,0.12)" }}><span className="text-amber-400/70">{icon}</span></div>}
      <h3 className="text-[10px] font-bold uppercase tracking-widest" style={{ color: "rgba(255,255,255,0.50)" }}>{title}</h3>
    </div>
    {children}
  </div>
);

const TripResult = ({ plan, onRegenerate, onPlanNewTrip, regenerateCount, weatherData, fromLocation, hotelsData, flightsData, trainsData, photosData, hotelPhotosData, readOnly = false }) => {
  const [saving, setSaving]         = useState(false);
  const [saved, setSaved]           = useState(false);
  const [saveError, setSaveError]   = useState("");
  const [pdfLoading, setPdfLoading] = useState(false);
  const [pdfError, setPdfError]     = useState("");
  const printRef = useRef(null);
  const maxRegens = 2;

  const [
    tripPlanLabel, personLabel, peopleLabel, styleLabel, disclaimer,
    hotelsTitle, perNight, itineraryTitle, dayLabel,
    morningLabel, afternoonLabel, eveningLabel,
    transportTitle, toDestLabel, localTransLabel,
    packingTitle, tipsTitle,
    regenLeft, stayHome, saveBtn, savingBtn, savedBtn,
    sharePdfBtn, pdfLoadingBtn, saveErrMsg, planNewTripLabel,
  ] = useTranslate([
    "Trip Plan", "person", "people", "style",
    "All prices are approximate estimates generated by AI — not guaranteed or bookable.",
    "Recommended Hotels", "/night", "Day-by-Day Itinerary", "Day",
    "Morning", "Afternoon", "Evening",
    "How to Get There & Around", "To Destination", "Local Transport",
    "Packing List", "Travel Tips",
    "left", "Maximum regenerations reached",
    "Save Trip", "Saving...", "Saved",
    "Download PDF", "Generating PDF...",
    "Failed to save trip. Please try again.", "Plan a new trip",
  ]);

  const handleSave = async () => {
    if (saved) return;
    setSaving(true); setSaveError("");
    try {
      await client.post("/trips/save", {
        plan: { ...plan, hotelsData: hotelsData || [], flightsData: flightsData || [], trainsData: trainsData || [], photosData: photosData || [], hotelPhotosData: hotelPhotosData || [], weatherData: weatherData || null },
        from_location: fromLocation || "",
      });
      setSaved(true);
    } catch { setSaveError(saveErrMsg); }
    finally { setSaving(false); }
  };

  const sanitize = (text) => {
    if (!text) return "";
    // eslint-disable-next-line no-control-regex
    return String(text).replace(/₹/g, "Rs.").replace(/\u20b9/g, "Rs.").replace(/¹/g, "Rs.").replace(/[^\x00-\x7F]/g, (c) => ({ "–": "-", "—": "-", "\u2019": "'", "\u2018": "'", "\u201C": '"', "\u201D": '"' }[c] || " "));
  };

  const handleDownloadPdf = () => {
    setPdfLoading(true); setPdfError("");
    try {
      const pdf = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
      const pageW = 210, pageH = 297, margin = 18, contentW = pageW - margin * 2;
      let y = margin;

      const gold       = [180, 130, 50];
      const goldLight  = [210, 165, 80];
      const inkDark    = [30,  24,  14];
      const inkMid     = [70,  58,  38];
      const inkLight   = [110, 95,  65];
      const cream      = [252, 248, 238];
      const paperDark  = [240, 232, 215];
      const paperMid   = [245, 239, 224];
      const lineColor  = [210, 195, 168];

      const fillPageBg = () => {
        pdf.setFillColor(...cream);
        pdf.rect(0, 0, pageW, pageH, "F");
      };
      fillPageBg();

      const checkPage = (needed = 10) => {
        if (y + needed > pageH - 16) {
          pdf.addPage();
          fillPageBg();
          pdf.setFillColor(...paperDark);
          pdf.rect(0, 0, pageW, 10, "F");
          pdf.setFontSize(7);
          pdf.setFont("helvetica", "italic");
          pdf.setTextColor(...inkLight);
          pdf.text(`Xplora AI  —  ${sanitize(plan.destination || "")}`, margin, 7);
          pdf.setFillColor(...gold);
          pdf.rect(0, 0, 3.5, 10, "F");
          y = 16;
        }
      };

      const sectionHeader = (title, emoji = "") => {
        y += 5; checkPage(16);
        pdf.setFillColor(...paperDark);
        pdf.roundedRect(margin - 2, y - 5, contentW + 4, 12, 2, 2, "F");
        pdf.setFillColor(...gold);
        pdf.roundedRect(margin - 2, y - 5, 4, 12, 1, 1, "F");
        pdf.setFontSize(9);
        pdf.setFont("helvetica", "bold");
        pdf.setTextColor(...gold);
        pdf.text((emoji ? emoji + "  " : "") + sanitize(title).toUpperCase(), margin + 5, y + 2.5);
        y += 10;
        pdf.setDrawColor(...lineColor);
        pdf.setLineWidth(0.3);
        pdf.line(margin, y, margin + contentW, y);
        y += 5;
      };

      const labelValue = (label, value, indent = margin + 3) => {
        checkPage(8);
        const valStr = sanitize(String(value || "—"));
        const labelW = 42;
        pdf.setFontSize(7.5);
        pdf.setFont("helvetica", "bold");
        pdf.setTextColor(...inkLight);
        pdf.text(sanitize(label), indent, y);
        pdf.setFont("helvetica", "normal");
        pdf.setTextColor(...inkDark);
        const lines = pdf.splitTextToSize(valStr, contentW - labelW - (indent - margin) - 4);
        lines.forEach((line, i) => {
          if (i > 0) { checkPage(6); y += 5; }
          pdf.text(line, indent + labelW, y);
        });
        y += 6.5;
      };

      const bulletItem = (text, indent = margin + 4) => {
        checkPage(7);
        pdf.setFillColor(...gold);
        pdf.circle(indent - 2, y - 1.2, 0.9, "F");
        pdf.setFontSize(8.5);
        pdf.setFont("helvetica", "normal");
        pdf.setTextColor(...inkDark);
        const lines = pdf.splitTextToSize(sanitize(text), contentW - (indent - margin) - 4);
        lines.forEach((line, i) => {
          if (i > 0) { checkPage(6); y += 5; }
          pdf.text(line, indent, y);
        });
        y += 6;
      };

      pdf.setFillColor(28, 22, 10);
      pdf.rect(0, 0, pageW, 62, "F");
      pdf.setFillColor(...gold);
      pdf.rect(0, 0, 5, 62, "F");
      pdf.setFontSize(11);
      pdf.setFont("helvetica", "bold");
      pdf.setTextColor(...gold);
      pdf.text("XPLORA", margin + 4, 14);
      pdf.setFontSize(7);
      pdf.setFont("helvetica", "normal");
      pdf.setTextColor(170, 148, 100);
      pdf.text("AI Travel Planner  —  Your complete trip plan", margin + 4, 20);
      pdf.setFontSize(26);
      pdf.setFont("helvetica", "bold");
      pdf.setTextColor(252, 244, 220);
      pdf.text(sanitize(String(plan.destination || "")).toUpperCase(), margin + 4, 40);
      const meta = [plan.duration, `${plan.people} ${plan.people === 1 ? "person" : "people"}`, plan.travelStyle ? `${plan.travelStyle} style` : null, plan.startDate ? `${sanitize(plan.startDate)} to ${sanitize(plan.endDate || "")}` : null].filter(Boolean).join("   |   ");
      pdf.setFontSize(8);
      pdf.setFont("helvetica", "normal");
      pdf.setTextColor(160, 138, 90);
      pdf.text(sanitize(meta), margin + 4, 52);
      if (fromLocation) {
        pdf.setFillColor(45, 36, 18);
        pdf.roundedRect(margin + 4, 55, 80, 6, 1.5, 1.5, "F");
        pdf.setFontSize(7);
        pdf.setFont("helvetica", "bold");
        pdf.setTextColor(...gold);
        pdf.text(`${sanitize(fromLocation)}  →  ${sanitize(plan.destination || "")}`, margin + 8, 59);
      }
      y = 72;

      pdf.setFontSize(9.5);
      pdf.setFont("helvetica", "italic");
      pdf.setTextColor(...inkMid);
      pdf.splitTextToSize(sanitize(plan.summary || ""), contentW).forEach((l) => { checkPage(7); pdf.text(l, margin, y); y += 6; });
      y += 3;
      pdf.setFillColor(255, 245, 210);
      pdf.roundedRect(margin, y, contentW, 9, 2, 2, "F");
      pdf.setDrawColor(...goldLight);
      pdf.setLineWidth(0.3);
      pdf.roundedRect(margin, y, contentW, 9, 2, 2, "S");
      pdf.setFontSize(7.5);
      pdf.setFont("helvetica", "italic");
      pdf.setTextColor(...inkLight);
      pdf.text("* All prices are approximate AI estimates — not guaranteed or bookable.", margin + 3, y + 6);
      y += 14;

      sectionHeader("Cost Breakdown", "");
      const cb = plan.costBreakdown || {};
      [["Accommodation", cb.stay], ["Travel", cb.travel], ["Food", cb.food], ["Activities", cb.activities], ["Taxi / Local", cb.taxi], ["Miscellaneous", cb.miscellaneous]].forEach(([l, v]) => { if (v) labelValue(l, v); });
      checkPage(16);
      y += 2;
      pdf.setFillColor(28, 22, 10);
      pdf.roundedRect(margin, y, contentW, 13, 2, 2, "F");
      pdf.setFontSize(8);
      pdf.setFont("helvetica", "bold");
      pdf.setTextColor(...goldLight);
      pdf.text("Total Estimated Cost:", margin + 4, y + 5.5);
      pdf.setFontSize(9);
      pdf.setTextColor(...gold);
      pdf.text(sanitize(cb.perPersonShare || cb.stay || "—"), margin + 4, y + 10.5);
      pdf.setFontSize(7.5);
      pdf.setFont("helvetica", "normal");
      pdf.setTextColor(170, 148, 100);
      pdf.text(`Per person share: ${sanitize(cb.perPersonShare || "—")}`, pageW - margin - 60, y + 8);
      y += 18;

      sectionHeader("AI Suggested Hotels", "");
      (plan.hotels || []).forEach((hotel, i) => { checkPage(28); pdf.setFillColor(...paperMid); pdf.roundedRect(margin, y - 2, contentW, 24, 2, 2, "F"); pdf.setFontSize(9.5); pdf.setFont("helvetica", "bold"); pdf.setTextColor(...inkDark); pdf.text(`${i + 1}.  ${sanitize(hotel.name)}`, margin + 4, y + 5); pdf.setFontSize(8); pdf.setFont("helvetica", "bold"); pdf.setTextColor(...gold); const priceText = sanitize(hotel.pricePerNight || "") + " / night"; pdf.text(priceText, pageW - margin - pdf.getTextWidth(priceText) - 4, y + 5); pdf.setFontSize(7.5); pdf.setFont("helvetica", "normal"); pdf.setTextColor(...inkLight); pdf.text(`Area: ${sanitize(hotel.area || "—")}   |   Rating: ${sanitize(String(hotel.rating || "—"))}`, margin + 4, y + 11); pdf.setFontSize(8); pdf.setFont("helvetica", "italic"); pdf.setTextColor(...inkMid); const reasonLines = pdf.splitTextToSize(sanitize(hotel.reason || ""), contentW - 10); reasonLines.slice(0, 2).forEach((rl, ri) => { pdf.text(rl, margin + 4, y + 17 + ri * 4.5); }); y += 28; });

      sectionHeader("Day-by-Day Itinerary", "");
      (plan.itinerary || []).forEach((day) => { checkPage(44); pdf.setFillColor(28, 22, 10); pdf.roundedRect(margin, y - 3, contentW, 11, 2, 2, "F"); pdf.setFillColor(...gold); pdf.roundedRect(margin, y - 3, 4, 11, 1, 1, "F"); pdf.setFontSize(9); pdf.setFont("helvetica", "bold"); pdf.setTextColor(252, 244, 220); pdf.text(`DAY ${day.day}  —  ${sanitize(day.title || "")}`, margin + 8, y + 4.5); pdf.setFontSize(7.5); pdf.setFont("helvetica", "normal"); pdf.setTextColor(160, 138, 90); pdf.text(`Est: ${sanitize(day.estimatedDayCost || "—")}`, pageW - margin - 34, y + 4.5); y += 13; pdf.setFillColor(...paperMid); const cardStartY = y; const cardHeight = 36 + (day.food?.length > 0 ? 8 : 0); checkPage(cardHeight); pdf.roundedRect(margin, y - 1, contentW, cardHeight, 2, 2, "F"); pdf.setFontSize(7.5); pdf.setFont("helvetica", "bold"); pdf.setTextColor(180, 130, 50); pdf.text("MORNING", margin + 5, y + 6); pdf.setFontSize(8); pdf.setFont("helvetica", "normal"); pdf.setTextColor(...inkDark); pdf.splitTextToSize(sanitize(day.morning || ""), contentW - 12).slice(0, 2).forEach((l, li) => pdf.text(l, margin + 5, y + 11 + li * 4.5)); pdf.setFontSize(7.5); pdf.setFont("helvetica", "bold"); pdf.setTextColor(160, 100, 30); pdf.text("AFTERNOON", margin + 5, y + 22); pdf.setFontSize(8); pdf.setFont("helvetica", "normal"); pdf.setTextColor(...inkDark); pdf.splitTextToSize(sanitize(day.afternoon || ""), contentW - 12).slice(0, 2).forEach((l, li) => pdf.text(l, margin + 5, y + 27 + li * 4.5)); const colR = margin + contentW / 2 + 2; pdf.setFontSize(7.5); pdf.setFont("helvetica", "bold"); pdf.setTextColor(80, 130, 170); pdf.text("EVENING", colR, y + 6); pdf.setFontSize(8); pdf.setFont("helvetica", "normal"); pdf.setTextColor(...inkDark); pdf.splitTextToSize(sanitize(day.evening || ""), contentW / 2 - 8).slice(0, 2).forEach((l, li) => pdf.text(l, colR, y + 11 + li * 4.5)); if (day.food?.length > 0) { pdf.setFontSize(7.5); pdf.setFont("helvetica", "bold"); pdf.setTextColor(...inkLight); pdf.text("FOOD:", margin + 5, y + cardHeight - 5); pdf.setFont("helvetica", "normal"); pdf.setTextColor(...inkMid); pdf.text(sanitize(day.food.slice(0, 4).join("  •  ")), margin + 20, y + cardHeight - 5); } y += cardHeight + 5; void cardStartY; });

      sectionHeader("Getting There & Around", "");
      checkPage(22); pdf.setFillColor(...paperMid); pdf.roundedRect(margin, y - 1, contentW, 18, 2, 2, "F"); pdf.setFontSize(7.5); pdf.setFont("helvetica", "bold"); pdf.setTextColor(80, 130, 180); pdf.text("TO DESTINATION", margin + 4, y + 6); pdf.setFontSize(8.5); pdf.setFont("helvetica", "normal"); pdf.setTextColor(...inkDark); pdf.splitTextToSize(sanitize(plan.transport?.toDestination || "—"), contentW - 8).slice(0, 2).forEach((l, li) => pdf.text(l, margin + 4, y + 11 + li * 5)); y += 22;
      checkPage(22); pdf.setFillColor(...paperMid); pdf.roundedRect(margin, y - 1, contentW, 18, 2, 2, "F"); pdf.setFontSize(7.5); pdf.setFont("helvetica", "bold"); pdf.setTextColor(60, 150, 100); pdf.text("LOCAL TRANSPORT", margin + 4, y + 6); pdf.setFontSize(8.5); pdf.setFont("helvetica", "normal"); pdf.setTextColor(...inkDark); pdf.splitTextToSize(sanitize(plan.transport?.localTransport || "—"), contentW - 8).slice(0, 2).forEach((l, li) => pdf.text(l, margin + 4, y + 11 + li * 5)); y += 22;

      if (weatherData?.ai_summary) { sectionHeader("Weather Info", ""); checkPage(20); pdf.setFillColor(235, 248, 255); pdf.roundedRect(margin, y - 1, contentW, 18, 2, 2, "F"); pdf.setDrawColor(150, 190, 220); pdf.setLineWidth(0.3); pdf.roundedRect(margin, y - 1, contentW, 18, 2, 2, "S"); pdf.setFontSize(8.5); pdf.setFont("helvetica", "normal"); pdf.setTextColor(40, 80, 120); pdf.splitTextToSize(sanitize(weatherData.ai_summary), contentW - 8).slice(0, 3).forEach((l, li) => { pdf.text(l, margin + 4, y + 5 + li * 5.5); }); y += 22; }

      if (hotelsData?.length > 0) { sectionHeader("Live Hotel Prices", ""); hotelsData.slice(0, 5).forEach((hotel, i) => { checkPage(18); pdf.setFillColor(...paperMid); pdf.roundedRect(margin, y - 1, contentW, 14, 2, 2, "F"); pdf.setFontSize(8.5); pdf.setFont("helvetica", "bold"); pdf.setTextColor(...inkDark); pdf.text(`${i + 1}.  ${sanitize(hotel.name || hotel.hotel_name || "Hotel")}`, margin + 4, y + 5); pdf.setFontSize(8); pdf.setFont("helvetica", "bold"); pdf.setTextColor(...gold); const p = sanitize(String(hotel.price || hotel.rate_per_night || "")); if (p) pdf.text(p + " / night", pageW - margin - pdf.getTextWidth(p + " / night") - 4, y + 5); pdf.setFontSize(7.5); pdf.setFont("helvetica", "normal"); pdf.setTextColor(...inkLight); const rating = hotel.rating || hotel.review_score; if (rating) pdf.text(`Rating: ${sanitize(String(rating))}`, margin + 4, y + 11); y += 17; }); }

      if (flightsData?.length > 0) { sectionHeader("Available Flights", ""); flightsData.slice(0, 4).forEach((flight, i) => { checkPage(18); pdf.setFillColor(...paperMid); pdf.roundedRect(margin, y - 1, contentW, 14, 2, 2, "F"); pdf.setFontSize(8.5); pdf.setFont("helvetica", "bold"); pdf.setTextColor(...inkDark); pdf.text(sanitize(flight.airline || flight.carrier || `Flight ${i + 1}`), margin + 4, y + 5); pdf.setFontSize(8); pdf.setFont("helvetica", "bold"); pdf.setTextColor(...gold); const fp = sanitize(String(flight.price || flight.fare || "")); if (fp) pdf.text(fp, pageW - margin - pdf.getTextWidth(fp) - 4, y + 5); pdf.setFontSize(7.5); pdf.setFont("helvetica", "normal"); pdf.setTextColor(...inkLight); if (flight.duration) pdf.text(`Duration: ${sanitize(String(flight.duration))}`, margin + 4, y + 11); y += 17; }); }

      if (trainsData?.length > 0) { sectionHeader("Available Trains", ""); trainsData.slice(0, 4).forEach((train, i) => { checkPage(22); pdf.setFillColor(...paperMid); pdf.roundedRect(margin, y - 1, contentW, 17, 2, 2, "F"); pdf.setFontSize(8.5); pdf.setFont("helvetica", "bold"); pdf.setTextColor(...inkDark); pdf.text(sanitize(train.train_name || train.name || `Train ${i + 1}`), margin + 4, y + 5); pdf.setFontSize(7.5); pdf.setFont("helvetica", "normal"); pdf.setTextColor(...inkLight); const parts = [train.departure ? `Dep: ${sanitize(String(train.departure))}` : null, train.arrival ? `Arr: ${sanitize(String(train.arrival))}` : null, train.duration ? `${sanitize(String(train.duration))}` : null].filter(Boolean).join("   |   "); if (parts) pdf.text(parts, margin + 4, y + 12); y += 20; }); }

      sectionHeader("Packing List", "");
      (plan.packingEssentials || []).forEach((item) => bulletItem(item));

      sectionHeader("Travel Tips", "");
      (plan.travelTips || []).forEach((tip, i) => { checkPage(10); pdf.setFontSize(8.5); pdf.setFont("helvetica", "bold"); pdf.setTextColor(...gold); pdf.text(`${i + 1}.`, margin + 3, y); pdf.setFont("helvetica", "normal"); pdf.setTextColor(...inkDark); const lines = pdf.splitTextToSize(sanitize(tip), contentW - 12); lines.forEach((l, li) => { if (li > 0) { checkPage(6); y += 5; } pdf.text(l, margin + 10, y); }); y += 6.5; });

      const totalPages = pdf.internal.getNumberOfPages();
      for (let p = 1; p <= totalPages; p++) { pdf.setPage(p); pdf.setFillColor(...paperDark); pdf.rect(0, pageH - 11, pageW, 11, "F"); pdf.setDrawColor(...lineColor); pdf.setLineWidth(0.3); pdf.line(margin, pageH - 11, pageW - margin, pageH - 11); pdf.setFontSize(7); pdf.setFont("helvetica", "normal"); pdf.setTextColor(...inkLight); pdf.text("Generated by Xplora — AI Travel Planner", margin, pageH - 5); pdf.setFont("helvetica", "bold"); pdf.setTextColor(...gold); pdf.text(`Page ${p} of ${totalPages}`, pageW - margin - 18, pageH - 5); }

      pdf.save(`Xplora_${(plan.destination || "Trip").replace(/\s+/g, "_")}_Plan.pdf`);
    } catch (err) {
      console.error("PDF failed:", err);
      setPdfError(`PDF failed: ${err.message}`);
    } finally {
      setPdfLoading(false);
    }
  };

  const glassCard = { background: "rgba(255,255,255,0.07)", backdropFilter: "blur(20px)", WebkitBackdropFilter: "blur(20px)", border: "1px solid rgba(255,255,255,0.14)" };
  const innerCard = { background: "rgba(255,255,255,0.05)", border: "1px solid rgba(255,255,255,0.10)" };

  return (
    <div className="w-full max-w-2xl" ref={printRef}>
      <WeatherBanner weatherData={weatherData} />
      <div id="trip-pdf-content">
        <div className="mb-2 px-0.5">
          <span className="inline-flex items-center gap-1.5 text-[10px] font-bold text-amber-400 uppercase tracking-widest bg-amber-400/10 border border-amber-400/25 px-3 py-1 rounded-full">✦ {tripPlanLabel}</span>
        </div>

        {/* Trip hero card */}
        <div className="rounded-2xl p-4 md:p-6 mb-4 shadow-xl" style={glassCard}>
          <div className="h-px w-12 bg-amber-400 mb-4" />
          <div className="flex justify-between items-start gap-3">
            <div className="flex flex-col gap-2 min-w-0">
              {/* Smaller font on mobile so it doesn't overflow */}
              <h2 className="font-serif text-2xl md:text-4xl font-black text-white leading-tight">{plan.destination}</h2>
              <div className="flex flex-wrap items-center gap-x-3 gap-y-1">
                {[plan.duration, `${plan.people} ${plan.people === 1 ? personLabel : peopleLabel}`, `${plan.travelStyle} ${styleLabel}`].map((item, i) => <span key={i} className="text-xs text-white/60">{item}</span>)}
              </div>
            </div>
            <span className="shrink-0 text-[10px] px-3 py-1.5 rounded-full font-bold whitespace-nowrap uppercase tracking-widest hidden sm:inline-block" style={{ background: "rgba(255,255,255,0.08)", border: "1px solid rgba(255,255,255,0.14)", color: "rgba(255,255,255,0.45)" }}>Xplora AI</span>
          </div>
          <p className="text-white/65 text-sm mt-4 leading-relaxed font-light">{plan.summary}</p>
        </div>

        {/* Disclaimer */}
        <div className="bg-amber-400/8 border border-amber-400/20 rounded-xl px-4 py-3 mb-4 flex items-start gap-2.5">
          <svg className="w-4 h-4 text-amber-400 shrink-0 mt-0.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}><path strokeLinecap="round" strokeLinejoin="round" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" /></svg>
          <p className="text-xs text-amber-400/80">{disclaimer}</p>
        </div>

        {/* Destination photos — 2 cols on mobile, 4 on sm+ */}
        {photosData?.length > 0 && (
          <div className="mb-4">
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-1.5 rounded-2xl overflow-hidden">
              {photosData.slice(0, 4).map((photo, i) => (
                <div key={i} className="h-28 sm:h-32 overflow-hidden rounded-xl">
                  <img src={photo.thumb} alt={photo.alt || plan.destination} className="w-full h-full object-cover hover:scale-105 transition-transform duration-300" />
                </div>
              ))}
            </div>
            <p className="text-[10px] text-white/20 mt-1.5 text-right">Photos via Xplora</p>
          </div>
        )}

        <TripCostSplitter costBreakdown={plan.costBreakdown} people={plan.people} totalBudget={plan.totalBudget} />
        <HotelsCard hotels={hotelsData} hotelPhotos={hotelPhotosData} />
        <TrainsCard trains={trainsData} />

        {/* AI Suggested Hotels */}
        <Section title={hotelsTitle} icon={<svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}><path strokeLinecap="round" strokeLinejoin="round" d="M2.25 12l8.954-8.955c.44-.439 1.152-.439 1.591 0L21.75 12M4.5 9.75v10.125c0 .621.504 1.125 1.125 1.125H9.75v-4.875c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125V21h4.125c.621 0 1.125-.504 1.125-1.125V9.75M8.25 21h8.25" /></svg>}>
          <div className="flex flex-col gap-2.5">
            {plan.hotels.map((hotel, i) => (
              <div key={i} className="rounded-xl p-4 transition-all duration-200" style={innerCard}>
                <div className="flex justify-between items-start gap-3">
                  <div className="min-w-0">
                    <p className="font-medium text-white/90 text-sm leading-snug">{hotel.name}</p>
                    <p className="text-xs text-white/45 mt-0.5 truncate flex items-center gap-1"><svg className="w-3 h-3 shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}><path strokeLinecap="round" strokeLinejoin="round" d="M15 10.5a3 3 0 11-6 0 3 3 0 016 0zM19.5 10.5c0 7.142-7.5 11.25-7.5 11.25S4.5 17.642 4.5 10.5a7.5 7.5 0 1115 0z" /></svg>{hotel.area}</p>
                  </div>
                  <div className="text-right shrink-0">
                    <p className="font-serif font-bold text-amber-400 text-sm">{hotel.pricePerNight}<span className="text-[10px] text-white/35 font-normal">{perNight}</span></p>
                    <div className="flex items-center gap-1 justify-end mt-0.5"><svg className="w-3 h-3 text-amber-400 fill-amber-400" viewBox="0 0 24 24"><path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"/></svg><p className="text-xs text-white/50">{hotel.rating}</p></div>
                  </div>
                </div>
                <p className="text-xs text-white/50 mt-2.5 leading-relaxed font-light">{hotel.reason}</p>
              </div>
            ))}
          </div>
        </Section>

        {/* Itinerary — 1 col on mobile, 2 cols on sm+ */}
        <Section title={itineraryTitle} icon={<svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}><path strokeLinecap="round" strokeLinejoin="round" d="M6.75 3v2.25M17.25 3v2.25M3 18.75V7.5a2.25 2.25 0 012.25-2.25h13.5A2.25 2.25 0 0121 7.5v11.25m-18 0A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75m-18 0v-7.5A2.25 2.25 0 015.25 9h13.5A2.25 2.25 0 0121 11.25v7.5" /></svg>}>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            {plan.itinerary.map((day) => (
              <div key={day.day} className="rounded-xl overflow-hidden flex flex-col" style={innerCard}>
                <div className="px-4 py-3 flex justify-between items-start gap-2 border-b" style={{ background: "rgba(255,255,255,0.05)", borderColor: "rgba(255,255,255,0.08)" }}>
                  <div className="min-w-0">
                    <span className="text-[10px] font-bold text-amber-400 uppercase tracking-widest block">{dayLabel} {day.day}</span>
                    <p className="font-medium text-white/85 text-xs mt-0.5 leading-snug line-clamp-2">{day.title}</p>
                  </div>
                  <span className="shrink-0 text-[10px] bg-amber-400/10 border border-amber-400/25 text-amber-400 px-2 py-1 rounded-full font-bold whitespace-nowrap">~{day.estimatedDayCost}</span>
                </div>
                <div className="px-4 py-3 flex flex-col gap-2 flex-1">
                  {[{ label: morningLabel, text: day.morning, color: "text-amber-400" }, { label: afternoonLabel, text: day.afternoon, color: "text-orange-400" }, { label: eveningLabel, text: day.evening, color: "text-sky-400" }].map(({ label, text, color }) => (
                    <div key={label}><span className={`text-[10px] font-bold uppercase tracking-widest ${color}`}>{label}</span><p className="text-xs text-white/60 leading-snug mt-0.5 font-light">{text}</p></div>
                  ))}
                  {day.food?.length > 0 && <div className="flex flex-wrap gap-1 mt-1">{day.food.map((f, i) => <span key={i} className="text-[10px] bg-amber-400/10 text-amber-400 border border-amber-400/20 px-2 py-0.5 rounded-full">{f}</span>)}</div>}
                </div>
              </div>
            ))}
          </div>
        </Section>

        {/* Transport */}
        <Section title={transportTitle} icon={<svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}><path strokeLinecap="round" strokeLinejoin="round" d="M6 12L3.269 3.126A59.768 59.768 0 0121.485 12 59.77 59.77 0 013.27 20.876L5.999 12zm0 0h7.5" /></svg>}>
          <div className="flex flex-col gap-2.5">
            {[{ label: toDestLabel, text: plan.transport.toDestination, color: "text-sky-400" }, { label: localTransLabel, text: plan.transport.localTransport, color: "text-emerald-400" }].map(({ label, text, color }) => (
              <div key={label} className="rounded-xl p-4" style={innerCard}><p className={`text-[10px] font-bold uppercase tracking-widest mb-1.5 ${color}`}>{label}</p><p className="text-sm text-white/65 leading-relaxed font-light">{text}</p></div>
            ))}
          </div>
        </Section>

        <WeatherCard weatherData={weatherData} tripStartDate={plan.startDate} tripEndDate={plan.endDate} />

        {/* Packing + Tips — 1 col on mobile, 2 cols on sm+ */}
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 mb-4">
          {[{ title: packingTitle, items: plan.packingEssentials }, { title: tipsTitle, items: plan.travelTips }].map(({ title, items }) => (
            <div key={title} className="rounded-2xl p-4 md:p-5" style={glassCard}>
              <p className="text-[10px] font-bold text-white/40 uppercase tracking-widest mb-4">{title}</p>
              <div className="flex flex-col gap-2">
                {items.map((item, i) => <div key={i} className="flex items-start gap-2"><div className="w-1 h-1 rounded-full bg-amber-400 shrink-0 mt-1.5" /><p className="text-xs text-white/65 leading-relaxed font-light">{item}</p></div>)}
              </div>
            </div>
          ))}
        </div>

        <div className="text-center py-6 border-t border-white/10 my-4">
          <p className="text-xs text-white/30">Trip planned with <span className="font-serif font-bold text-amber-400">Xplora</span> — AI Travel Planner</p>
        </div>
      </div>

      {/* Action Buttons */}
      <div className="mb-6">
        {!readOnly && saveError && (
          <div className="mb-3 text-xs text-red-400 bg-red-500/10 border border-red-500/20 rounded-xl px-4 py-2.5 flex items-center gap-2">
            <svg className="w-3.5 h-3.5 shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}><path strokeLinecap="round" strokeLinejoin="round" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" /></svg>
            {saveError}
          </div>
        )}
        {!readOnly && saved && (
          <div className="mb-3 text-xs text-emerald-400 bg-emerald-500/10 border border-emerald-500/20 rounded-xl px-4 py-2.5 text-center">
            Trip saved — find it in <span className="font-bold">My Trips</span>.
          </div>
        )}
        {pdfError && (
          <div className="mb-3 text-xs text-red-400 bg-red-500/10 border border-red-500/20 rounded-xl px-4 py-2.5">{pdfError}</div>
        )}

        {readOnly ? (
          <div className="flex justify-center">
            <button
              onClick={handleDownloadPdf}
              disabled={pdfLoading}
              className="px-8 py-3 rounded-xl font-semibold text-xs disabled:opacity-50 transition-all hover:-translate-y-0.5"
              style={{ background: "rgba(255,255,255,0.07)", border: "1px solid rgba(255,255,255,0.18)", color: "rgba(255,255,255,0.75)" }}
            >
              <span className="flex items-center gap-2">
                <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}><path strokeLinecap="round" strokeLinejoin="round" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" /></svg>
                {pdfLoading ? pdfLoadingBtn : sharePdfBtn}
              </span>
            </button>
          </div>
        ) : (
          /* Stack buttons on mobile to avoid overflow */
          <div className="flex flex-col sm:grid sm:grid-cols-3 gap-3">
            <button
              onClick={onRegenerate}
              disabled={regenerateCount >= maxRegens}
              className="w-full py-3.5 min-h-12 rounded-xl font-semibold text-xs disabled:opacity-30 disabled:cursor-not-allowed transition-all active:scale-[0.98]"
              style={{ background: "rgba(255,255,255,0.07)", border: "1px solid rgba(255,255,255,0.12)", color: "rgba(255,255,255,0.60)" }}
            >
              {regenerateCount >= maxRegens ? stayHome : `↺ Regenerate (${maxRegens - regenerateCount} ${regenLeft})`}
            </button>
            <button
              onClick={handleSave}
              disabled={saving || saved}
              className="w-full py-3.5 min-h-12 rounded-xl bg-amber-400 hover:bg-amber-300 text-stone-900 font-bold text-xs disabled:opacity-50 transition-all hover:-translate-y-0.5 active:scale-[0.98]"
            >
              {saving ? savingBtn : saved ? savedBtn : saveBtn}
            </button>
            <button
              onClick={handleDownloadPdf}
              disabled={pdfLoading}
              className="w-full py-3.5 min-h-12 rounded-xl font-semibold text-xs disabled:opacity-50 transition-all active:scale-[0.98]"
              style={{ background: "rgba(255,255,255,0.07)", border: "1px solid rgba(255,255,255,0.12)", color: "rgba(255,255,255,0.60)" }}
            >
              {pdfLoading ? pdfLoadingBtn : sharePdfBtn}
            </button>
          </div>
        )}
      </div>

      {/* Plan new trip — BOTTOM */}
      {!readOnly && onPlanNewTrip && (
        <div className="pb-8 flex justify-center">
          <button
            onClick={onPlanNewTrip}
            className="flex items-center gap-2 text-xs font-semibold text-white/30 hover:text-amber-400 transition-colors border border-white/10 hover:border-amber-400/30 px-5 py-2.5 rounded-full"
          >
            <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}><path strokeLinecap="round" strokeLinejoin="round" d="M12 4v16m8-8H4" /></svg>
            {planNewTripLabel}
          </button>
        </div>
      )}
    </div>
  );
};

export default TripResult;